### ISSUE TITLE
A few questions.....

### ISSUE THREAD

**Issue by chaoscreater** [targor/Line-Sticker-Downloader#2]
Hi, 

Thanks for making this tool. I've checked the settings and don't see where I can set the default download path. How can I configure this?

Furthermore, what does "Download all available collections" do? Does that download ALL of the stickers in the Line store?

Lastly, one of the collections that I downloaded only contains 2 stickers:

![image](https://user-images.githubusercontent.com/18227319/163537842-fcbdb0c5-1014-4ba6-828f-6620cfbe9837.png)

But here, you can see there are more than 2 stickers and you can copy them to clipboard:
https://store.line.me/stickershop/product/15492/en

**Comment by targor** [comment]
Hi

i have updated the code and added a sticker path option to the settings dialog.

I also corrected a issue where a collection could not be downloaded correctly. Maybe this will also fix your problem with the missing images. It could be the case, that some images cannot be downloaded due to connection timeouts, server errors, parsing errors and so on. But in general it should load everything.

You can find the release here: https://github.com/targor/Line-Sticker-Downloader/releases/tag/Release_1.0.1


The "Download all available collections" does exactly as you suggested.. it downloads everything it can find :).

**Comment by targor** [comment]
I updated the program, there seemed to be an issue with folders that have unicode in them where the apng converter died :D.. should be fixed now. Please tell me if you encounter other issues.

You can download the setup here: https://github.com/targor/Line-Sticker-Downloader/releases/download/Release_1.0.2/setup_1_0_2.exe

**Comment by thewayur** [comment]
issue not resolved, 
i double checked that i m using v1.0.2 

btw what does apng converter doing? converting them to gif?


also can i request to make a worthy tgs-to-apng converter?
there is lib already available here, but i would love gui, specially the simplicity u have provided 👍

**Comment by targor** [comment]
> what does apng converter doing? converting them to gif? 

Exactly. it converts the apng file to an animated gif, als there a not so many imageviewers out there that can handle apng.

> if i uncheck the apng converter , it does not loop png file

Then maybe your imageviewer cannot handle apng. on windows you can use xnview, which can display it. Or use the "convert APNG" functionality :).

> also can i request to make a worthy tgs-to-apng converter?

If you can provide me the a link to the existing library for tgs, i may can write a gui wrappe for it. but as i do not have telegram, debugging is limited for me.

Now to your existing problem: I have checked some images that stopped downloading on my side and they are now loading without problems. Could you provide me with some names of sticker collections on your side, that are not working?

**Comment by thewayur** [comment]
i am using chrome browser, and other apng is looping perfectly as per their loop count. (i m web developer and have been using apng since years)

the bugs is found in "LINE_Characters_Cute_and_Soft" & "Beat_Brown" then i stopped testing it.
(these stickers is in first page, 3rd last row  of ur app)


tgs to apng library = [https://github.com/search?q=tgs+to+apng](url)
they are not hard to figure out in web based library, but for speed i wish to have it in windows

**Comment by targor** [comment]
Issue cannot be reproduced at the moment. Please reopen if it still happens in the newest version. (Be sure to clear all caches and use a clean download folder.)
